apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
    role: logging
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: p-es-db
  selector:
    app: elasticsearch
