apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging
  labels:
    app: elasticsearch-logging
spec:
  #type: NodePort
  ports:
  - port: 9200
    protocol: TCP
    targetPort: p-es-db
  selector:
    app: elasticsearch-logging
