apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-es-g
  labels:
    app: elasticsearch-logging
spec:
  replicas: 2
  selector:
    app: elasticsearch-logging
    color: "green"
  template:
    metadata:
      labels:
        app: elasticsearch-logging
        color: "green"
    spec:
      containers:
      - image: shinydocker/elasticsearch:1.1
        name: c-elasticsearch
        resources:
          limits:
            cpu: 100m
        ports:
        - containerPort: 9200
          name: p-es-db
          protocol: TCP
        - containerPort: 9300
          name: p-es-transport
          protocol: TCP
        volumeMounts:
        - name: v-es-persistence
          mountPath: /data
      volumes:
      #- name: v-es-persistence
      #- gcePersistentDisk:
      #-   pdName: elasticsearch-disk
      #-   fsType: ext4
      - name: v-es-persistence
        emptyDir: {}
