apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: kibana
    role: logging
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Kibana"
spec:
  ports:
  - port: 5601
    protocol: TCP
    targetPort: p-kibana-ui
  selector:
    app: kibana
