apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-kibana
  namespace: kube-system
  labels:
    app: kibana
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    app: kibana
  template:
    metadata:
      labels:
        app: kibana
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: c-kibana
        image: shinydocker/kibana:1.3
        resources:
          limits:
            cpu: 100m
        env:
          - name: "ELASTICSEARCH_URL"
            value: "http://elasticsearch:9200"
        ports:
        - containerPort: 5601
          name: p-kibana-ui
          protocol: TCP
