apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: c-kibana
        image: shinydocker/kibana:1.6
        imagePullPolicy: "Always"
        resources:
          limits:
            cpu: 100m
        env:
          - name: "ELASTICSEARCH_URL"
            value: "http://elasticsearch-logging:9200"
            #value: "http://elasticsearch-logging.default.svc.cluster.local:9200"
        ports:
        - containerPort: 5601
          name: p-kibana-ui
          protocol: TCP
